### ISSUE TITLE
genealogos: get a CycloneDX SBOM from Nix via HTTP

### ISSUE THREAD

**Issue by GuillaumeDesforges** [tweag/genealogos#20]
A long term goal would be for anyone to be able to host a service that makes the generation of SBOM from Nix accessible to anyone.

To that end, genealogos should provide an HTTP API to generate SBOM, so everyone can easily get an SBOM from a HTTP request.

Deliverables:
* Release of a new version of genealogos that includes an HTTP API server to generate a CycloneDX SBOM from a reference to a Nix flake
* Guide on how to run the web server
* Documentation for the API endpoints

```[tasklist]
### Tasks
- [ ] https://github.com/tweag/genealogos/issues/25
- [ ] https://github.com/tweag/genealogos/issues/28
- [ ] https://github.com/tweag/genealogos/issues/30
```
