### ISSUE TITLE
genealogos: incorporate metadata from built derivations

### ISSUE THREAD

**Issue by GuillaumeDesforges** [tweag/genealogos#22]
nixtract outputs metadata from the definitions in the Nix code, but some other information like closure size or runtime dependencies require building Nix derivations. In order to enrich the generated SBOM, genealogos needs to be able to incorporate such information, usually available in a binary cache server, called substituter in the Nix ecosystem.

Deliverables:
* Release of a new version of genealogos that includes which incorporates metadata from a Nix substituter to the output SBOM when available
* Updated documentations to explain the feature
```[tasklist]
### Tasks
- [ ] https://github.com/tweag/nixtract/issues/29
- [ ] https://github.com/tweag/genealogos/issues/35
- [x] Update documentation where applicable.
```

**Comment by ErinvanderVeen** [comment]
Resolved!
