### ISSUE TITLE
genealogos: output a CycloneDX SBOM from Nix via a terminal

### ISSUE THREAD

**Issue by GuillaumeDesforges** [tweag/genealogos#5]
Existing tools to generate SBOM from Nix (sbomnix, nixbom, bombon), are limited to derivations that have been realized in the Nix store, meaning packages that have been built and are available locally. nixtract, an open-source project developed at Tweag, can extract metadata about derivations without building them. Combining this data with Nix builtin capability to extract a dependency graph, we can build a SBOM generator that can be used by anyone, in the form of a command line tool.

Our first goal is to release an initial version of `genealogos` with minimal functionality.

```[tasklist]
### Tasks
- [ ] https://github.com/tweag/genealogos/issues/8
- [ ] https://github.com/tweag/genealogos/issues/3
- [ ] https://github.com/tweag/genealogos/issues/2
- [ ] https://github.com/tweag/genealogos/issues/4
```

**Comment by henrirosten** [comment]
> Existing tools to generate SBOM from Nix (sbomnix, nixbom, bombon), are limited to derivations that have been realized in the > Nix store, meaning packages that have been built and are available locally.

Commenting the sbomnix part: it defaults to runtime dependencies, which indeed require realising the output locally, but can also work with buildtime dependencies in which case, outputs don't have to be realised. I tried clarify this in: https://github.com/tiiuae/sbomnix/tree/main?tab=readme-ov-file#buildtime-vs-runtime-dependencies and https://github.com/tiiuae/sbomnix/tree/main?tab=readme-ov-file#generate-sbom-including-buildtime-dependencies.

Hope this clarifies, also, let me know if you have any other questions about sbomnix.

**Comment by GuillaumeDesforges** [comment]
It works.
